---
name: XML-Grammar-Screenplay
version: 0.0503
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  CPAN distribution implementing an XML grammar for 
  screenplays.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
build_requires:
  File::Find: 0
  Test::More: 0
  Test::XML: 0
requires:
  Carp: 0
  Data::Dumper: 0
  HTML::Entities: 0
  List::Util: 0
  Moose: 0
  Parse::RecDescent: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  warnings: 0
configure_requires:
  Module::Build: 0.34
provides:
  XML::Grammar::Screenplay:
    file: lib/XML/Grammar/Screenplay.pm
    version: 0.0503
  XML::Grammar::Screenplay::App::FromProto:
    file: lib/XML/Grammar/Screenplay/App/FromProto.pm
  XML::Grammar::Screenplay::App::ToDocBook:
    file: lib/XML/Grammar/Screenplay/App/ToDocBook.pm
  XML::Grammar::Screenplay::App::ToHTML:
    file: lib/XML/Grammar/Screenplay/App/ToHTML.pm
  XML::Grammar::Screenplay::Base:
    file: lib/XML/Grammar/Screenplay/Base.pm
  XML::Grammar::Screenplay::FromProto:
    file: lib/XML/Grammar/Screenplay/FromProto.pm
    version: 0.0503
  XML::Grammar::Screenplay::FromProto::Node:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Comment:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Description:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Element:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::InnerDesc:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::List:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Paragraph:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Saying:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::Text:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Node::WithContent:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Nodes:
    file: lib/XML/Grammar/Screenplay/FromProto/Nodes.pm
  XML::Grammar::Screenplay::FromProto::Parser:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser.pm
  XML::Grammar::Screenplay::FromProto::Parser::PRD:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser/PRD.pm
  XML::Grammar::Screenplay::FromProto::Parser::QnD:
    file: lib/XML/Grammar/Screenplay/FromProto/Parser/QnD.pm
  XML::Grammar::Screenplay::ToDocBook:
    file: lib/XML/Grammar/Screenplay/ToDocBook.pm
    version: 0.0503
  XML::Grammar::Screenplay::ToHTML:
    file: lib/XML/Grammar/Screenplay/ToHTML.pm
    version: 0.0503
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
